package consumat;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import decision.DecisionResult;
import reader.ReadData;

import org.apache.commons.math3.distribution.NormalDistribution;

import activity.Activity;
import agent.Farm;

/** 
 * This class contains the main() method of this programme. 
 * Full simulation runs inside of the main() method by creating farm objects and making decisions for each farm.
 *
 */
public class Consumat {
	static long line_counter = 0;
	static int file_counter = 1;
	static String origFileName = createFileName();										           // file name for logging
	static String FileName = origFileName + String.format("%d",0);								   // given enough lines in the log file, we need to start a new file
		
	public static void main(String[] args) {
		System.out.println("Starting Model");

		if (args.length < 1) {
			System.out.println("input number of iterations");
			System.exit(0);
		}
		
		if (args.length > 1) {
			System.out.println("ABM version number: 1.0");
		}

		ReadData reader = new ReadData();									   // read all input data files
		List<Farm>     allFarms = reader.getFarms();					       // build set of farms 
		List<Double> simulatedIncomeForFarms = new ArrayList<Double>();		   // list of all farm incomes
		
		initializeRegionIncomeChangePercent(allFarms);						   // only take into account the preset values
		
		for (int year = 1; year <= Integer.parseInt(args[0]); year++) {							       // run simulation for a set of years, getting updated income and products	
			System.out.println(String.format("year %d", year));				
			
			CreateGamsFile(allFarms, year, simulatedIncomeForFarms);
			RunGams(allFarms);
			simulatedIncomeForFarms = readGamsResults(allFarms);
			updateRegionIncomeChangePercent(allFarms,simulatedIncomeForFarms); // after time step update the percent change for population
		}

		System.out.println("Complete");
	}
	
	/**
	 * This function updates incomes for farms and then make the farm decision and resulting strategy choice for each farm. 
	 * Each farm then appends this choice to the simulation control file
	 * 
	 * @param allFarms list of all farms in the system
	 * @param year indicator of time period
	 * @param simulatedIncomeForFarms income generated by the simulation of the previous period
	 */
	private static void CreateGamsFile(List<Farm> allFarms, int year, List<Double> simulatedIncomeForFarms) {
		double income = 0;																	       // specific income of farm 
		double probability = 0;																       // probability of income occurring
		
		int farmIndex = 0;																		   // index of specific farm in list

		File f = new File("p_allowedStratPrePost.csv");										       // delete last time period's simulation file
		if (f.exists()) {f.delete();}
		
		for (Farm farm : allFarms) {
			if (year == 1) {															           // ignore first year as we already have that initialized with input file
				income = -1;
				probability = 0.5;
			} else {
				double mean = mean(simulatedIncomeForFarms)*100;
				double std = std(simulatedIncomeForFarms)*100;
				NormalDistribution normal = new NormalDistribution(mean, std);			           // distribution of possible incomes
				income = simulatedIncomeForFarms.get(farmIndex);
				probability = normal.cumulativeProbability(income);
			}
			
			farm.updateFarmData(allFarms, income, probability);
			List<String> possibleActivitySet = farm.makeDecision(allFarms);      
			
			System.out.print(farm.getFarmName() + " current activity: ");
			for (Activity act: farm.getCurrentActivities() ) System.out.print(act.getName() + " ");
			System.out.print("\n");
			
			System.out.print(farm.getFarmName() + " possible activity: ");
			for (String act: possibleActivitySet) System.out.print(act + " ");
			System.out.print("\n");
			
			DecisionResult decision = new DecisionResult(farm.getPreferences().getDataElementName(), farm.getFarmName(), year, farm.getLearningRate(), farm.getStrategy(), farm.getIncomeHistory().get(0), farm.getCurrentActivities(), possibleActivitySet, farm);

			line_counter++;
			if (line_counter > 999999) {
				FileName = origFileName + String.format("%d",file_counter);
				file_counter++;
				line_counter = 0;
			} 
			decision.appendLogFile(FileName);
			decision.appendGamsFile();													   // create a file 'p_allowedStrat' which contains the gams options for each farm
			farm.updateExperiencePlusAge();                              				   // each time period update experience
			farmIndex++;
		}

		System.out.println("Created Gams simulation file");
	}
	
	/** 
	 * This function runs GAMS simulation based on input file created while looping through all farms.
	 * 
	 * @param allFarms list of all farms in system
	 */
	private static void RunGams(List<Farm> allFarms) {
		Runtime runtime = Runtime.getRuntime();								   // java runtime to run commands
		
		File f = new File("Grossmargin_P4,00.csv");							   // delete previous results file before new run
		f.delete();
		
		try {
			String name = System.getProperty("os.name").toLowerCase();;
			if (name.startsWith("win") ){
				runtime.exec("cmd /C" + "run_gams.bat");						   // actually run command
			}
			if (name.startsWith("mac")) {
				runtime.exec("/bin/bash -c ./run_gams_mac.command");				   // actually run command
			}
			System.out.println("Starting gams model");
			System.out.println("Waiting for gams results to be generated");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	/** 
	 * This function reads GAMS file and set the income and activities based on that file
	 * @param allFarms list of all farms in system
	 * @return incomes is a list of all incomes for each farm
	 */
	@SuppressWarnings("unchecked")
	private static List<Double> readGamsResults(List<Farm> allFarms) {
		List<Double> incomes = new ArrayList<Double>();						   // list of all farm incomes
		List<Activity> activity = new ArrayList<Activity>();	   	 	       // list of all farm activities selected by LP model
		
		List<Object> data = readIncome();            					       // read all results data
		incomes = (List<Double>) data.get(0);
		activity = (List<Activity>) data.get(1);
		
		for (int i = 0; i < allFarms.size(); i++) {
			List<Activity> act = new ArrayList<Activity>();
			act.add(activity.get(i));
			allFarms.get(i).setCurrentActivites(act);
		}
		return incomes;
	}
	
	/**
	 * This function generates income values for each farm.
	 * 
	 * @return list of incomes and actions
	 */
	private static List<Object> readIncome() {													 
		ReadData reader = new ReadData();										   // read all input data files
		List<Object> data = reader.readIncomeResults();									
		return data;
	}

	/** 
	 * This function initializes the income growth rate of the population (in a region) for all farms.
	 * 
	 * @param allFarms list of all farms in region
	 */
	private static void initializeRegionIncomeChangePercent(List<Farm> allFarms) {
		double historicalRegionAverage = 0;
		List<Double> initIncome = new ArrayList<Double>();
		double thisYearAverage = 0;
		double percentChange;
		
		for (Farm farm: allFarms) {
			List<Double> income = new ArrayList<Double>(farm.getIncomeHistory());
			initIncome.add(income.get(0));
			income.remove(0);
			historicalRegionAverage = historicalRegionAverage + mean(income);
		}
		historicalRegionAverage = historicalRegionAverage/allFarms.size();
		thisYearAverage = mean(initIncome);
		
		percentChange = (thisYearAverage - historicalRegionAverage) / historicalRegionAverage;
		
		for (Farm farm: allFarms) {
			farm.setRegionIncomeChangePercent(percentChange);
		}
	}
	
	/** 
	 * This function update the income growth rates based on new income for farms.
	 * 
	 * @param allFarms list of all farms in region
	 * @param thisYearIncome list of income values for all farms
	 */
	private static void updateRegionIncomeChangePercent(List<Farm> allFarms, List<Double> thisYearIncome) {
		double historicalRegionAverage = 0;
		double thisYearAverage = mean(thisYearIncome);
		double percentChange;
		
		for (Farm farm: allFarms) {
			List<Double> income = new ArrayList<Double>(farm.getIncomeHistory());
			income.remove(0);
			historicalRegionAverage = historicalRegionAverage + mean(income);
		}
		historicalRegionAverage = historicalRegionAverage/allFarms.size();
		
		percentChange = (thisYearAverage - historicalRegionAverage) / historicalRegionAverage;
		
		for (Farm farm: allFarms) {
			farm.setRegionIncomeChangePercent(percentChange);
		}
	}
	
	/** 
	 * Return mean value of provided list 
	 * @param list of values to calculate mean with
	 * @return mean
	 */
	private static double mean(List<Double> list) {
		double mean = 0;												       // mean value to return
		
		for (int i = 0; i<list.size(); i++) {
			mean = mean + list.get(i);
		}
		
		return mean / list.size();
	}
	
	/**
	 * Calculate standard deviation of a list
	 * @param list
	 * @return std deviation value
	 */
	private static double std(List<Double> list) {
		double sd = 0;		
		for (int i=0; i<list.size();i++)
		{
		    sd = sd + Math.pow(list.get(i) - mean(list), 2);
		}
		
		sd = Math.sqrt(sd/list.size());
		return sd;
	}

	/** 
	 * Create generic file name so version number can be appended to end
	 * @return fileName
	 */
	public static String createFileName() {
		Calendar now = Calendar.getInstance();                             // Gets the current date and time
		int day = now.get(Calendar.DAY_OF_MONTH); 
		int month = now.get(Calendar.MONTH) + 1;
		int year_file = now.get(Calendar.YEAR);
		int hour = now.get(Calendar.HOUR);
		int minute = now.get(Calendar.MINUTE);	
		String fileName = String.format("Results-%d-%d-%d-%d-%d_v", day, month, year_file,hour, minute);
		
		return fileName;
	}
}


